name: Build README
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Autoformat README
        uses: cflynn07/github-action-til-autoformat-readme@1.2.0
        with:
          description: |
            공부 기록
          list_most_recent: 5
          date_format: "2006년 01월 02일 15:04"
          footer: "Updated by GitHub Actions"

      - name: List files for debugging
        run: |
          echo "Listing all files in the repository:"
          ls -la
          echo "Listing all Markdown files:"
          find . -name "*.md"

      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update README" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
