name: Build README
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Find and list .md files
        run: |
          echo "Found .md files:"
          find Certifications Spring -name "*.md" | tee md_files.txt

      - name: Autoformat README
        uses: cflynn07/github-action-til-autoformat-readme@1.2.0
        with:
          description: |
            공부 기록
          list_most_recent: 5
          date_format: "2006년 01월 02일 15:04"
          custom_tags: "Certifications/CIP, Spring"
          dir_table_of_contents: false
          dir_blacklist: |
            tree.txt
          categories_template: |
            ## 카테고리
            {CATEGORIES}
          included_file_extensions: |
            .md
          files_to_parse: md_files.txt

      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update README" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
