name: Update README

on:
  push:
    branches:
      - main

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update README
        run: |
          echo "# TIL" > README.md
          tree -tf --noreport -I '*~' --charset ascii | sed -e 's/| \+/*/g' -e 's/[|`]-\+/ */g' -e 's:\(* \)\(\(.*/\)\([^/]\+\)\):\1[\4](\2):g' >> README.md

      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md
          git commit -m "Update README"
          git push
