name: Update README

on:
  push:
    paths:
      - 'Certifications/CIP/**'
      - 'Spring/**'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update README
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          new_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^(Certifications/CIP|Spring)/.*\.md$')
          
          if [ -n "$new_files" ]; then
            echo "## 최근 업데이트" >> README.md
            echo "" >> README.md
          
            for file in $new_files; do
              echo "- [$(basename $file .md)](/$file)" >> README.md
            done
          
            git add README.md
            git commit -m "Update README with new links"
            git push
          fi
