name: Build README
on:
  push:
    branches:
      - main
    paths:
      - 'Certifications/CIP/**'
      - 'Spring/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Autoformat README
        uses: cflynn07/github-action-til-autoformat-readme@1.2.0
        with:
          description: |
            공부 기록
          list_most_recent: 5
          date_format: "2006년 01월 02일 15:04"
          custom_tags: "Certifications/CIP, Spring"
          dir_table_of_contents: false
          dir_blacklist: |
            tree.txt
          categories_template: |
            ## 카테고리

            {CATEGORIES}
